image: atlassian/default-image:2

pipelines:
  branches:
    develop:
      - step:
          name: 'Build front [develop]'
          image: node:12.16-alpine
          caches:
            - node
          size: 2x # Double resources available for this step.
          script:
            - apk update
            - apk add git
            - apk add --no-cache openssh
            - git submodule init && git submodule update
            - yarn package:install
            - yarn build:dev
    release/alpha:
      - step:
          name: 'Build and Deploy front [alpha]'
          image: node:12.16-alpine
          max-time: 10
          script:
            - apk update
            - apk add openssh
            - apk add sshpass
            - sshpass -p $ALPHA_DEVELOP_SVR_PASS ssh -o StrictHostKeyChecking=no $ALPHA_DEVELOP_SVR_USER@alpha-backend.premia.kr "deploy_alpha $BITBUCKET_REPO_SLUG"
      - step:
          name: 'Build and Deploy storybook [alpha]'
          trigger: manual 
          image: node:12.16-alpine
          max-time: 10
          script:
            - apk update
            - apk add openssh
            - apk add sshpass
            - sshpass -p $ALPHA_DEVELOP_SVR_PASS ssh -o StrictHostKeyChecking=no $ALPHA_DEVELOP_SVR_USER@alpha-backend.premia.kr "deploy_alpha storybook"
    release/beta:
      - step:
          name: 'Build front [beta]'
          image: node:12.16-alpine
          caches:
            - node
          services:
            - docker
          script:
            - apk update
            - apk add git
            - apk add --no-cache openssh
            - git submodule init && git submodule update
            - yarn package:install
            - yarn build:beta
            - docker build -f infra/Dockerfile-beta -t beta-$BITBUCKET_REPO_SLUG .
            - docker save --output tmp-image01.docker beta-$BITBUCKET_REPO_SLUG
          artifacts:
            - tmp-image01.docker
      - step:
          name: 'Deploy front [beta]'
          image: docker:git
          caches:
            - docker
            - pip
          services:
            - docker
          script:
            - docker load --input ./tmp-image01.docker
            - export DOCKER_API_VERSION=1.39
            - apk update && apk add bash
            - apk --no-cache add python3
            - apk add py3-pip
            - pip3 --no-cache-dir install awscli
            - chmod +x infra/aws_credential.sh
            - infra/aws_credential.sh
            - eval $(aws ecr get-login --no-include-email --region ap-northeast-2)
            - docker tag beta-$BITBUCKET_REPO_SLUG:latest 733773547159.dkr.ecr.ap-northeast-2.amazonaws.com/beta-$BITBUCKET_REPO_SLUG:$BITBUCKET_BUILD_NUMBER
            - docker tag beta-$BITBUCKET_REPO_SLUG:latest 733773547159.dkr.ecr.ap-northeast-2.amazonaws.com/beta-$BITBUCKET_REPO_SLUG:latest
            - docker push 733773547159.dkr.ecr.ap-northeast-2.amazonaws.com/beta-$BITBUCKET_REPO_SLUG:$BITBUCKET_BUILD_NUMBER
            - docker push 733773547159.dkr.ecr.ap-northeast-2.amazonaws.com/beta-$BITBUCKET_REPO_SLUG:latest
            - apk add jq
            - apk add curl
            - apk add --update-cache --upgrade curl
            - curl https://raw.githubusercontent.com/silinternational/ecs-deploy/master/ecs-deploy | tee /usr/bin/ecs-deploy
            - chmod +x /usr/bin/ecs-deploy
            - ecs-deploy -r ${AWS_REGION} -c beta-onepoint-front -n onepoint-front -i 733773547159.dkr.ecr.ap-northeast-2.amazonaws.com/beta-$BITBUCKET_REPO_SLUG:latest --skip-deployments-check
    release/production:
      - step:
          name: "Build [Production]"
          image: node:12.16-alpine
          services:
          - docker
          script: 
            - apk update
            - apk add git
            - git submodule init && git submodule update
            - yarn package:install
            - yarn build:beta
            - docker build -f infra/Dockerfile-prod -t prod-$BITBUCKET_REPO_SLUG .
            - docker save --output tmp-image.docker prod-$BITBUCKET_REPO_SLUG
          artifacts:
            - tmp-image.docker
      - step:
           name: "Deploy [Production]"
           image: docker:git
           services:
            - docker
           script: 
            - docker load --input ./tmp-image.docker
            - export DOCKER_API_VERSION=1.39
            - apk update && apk add bash
            - apk --no-cache add python3
            - apk add py3-pip
            - pip3 --no-cache-dir install awscli
            - chmod +x infra/aws_credential.sh
            - infra/aws_credential.sh
            - eval $(aws ecr get-login --no-include-email --region ap-northeast-2)
            - docker tag prod-$BITBUCKET_REPO_SLUG:latest 733773547159.dkr.ecr.ap-northeast-2.amazonaws.com/prod-$BITBUCKET_REPO_SLUG:$BITBUCKET_BUILD_NUMBER
            - docker tag prod-$BITBUCKET_REPO_SLUG:latest 733773547159.dkr.ecr.ap-northeast-2.amazonaws.com/prod-$BITBUCKET_REPO_SLUG:latest
            - docker push 733773547159.dkr.ecr.ap-northeast-2.amazonaws.com/prod-$BITBUCKET_REPO_SLUG:$BITBUCKET_BUILD_NUMBER
            - docker push 733773547159.dkr.ecr.ap-northeast-2.amazonaws.com/prod-$BITBUCKET_REPO_SLUG:latest