export const passenger = {
  passengerKey: 'MCFBRFQ-',
  name: {
    first: 'Daehee',
    middle: null,
    last: 'Jeong',
    title: null,
    suffix: null,
  },
  travelDocument: {
    documentTypeCode: 'P',
    passengerTravelDocumentKey: 'UCFLUiEg',
    birthCountry: 'KR',
    issuedByCode: 'KR',
    name: {
      first: 'DAEHEEADT',
      middle: null,
      last: 'JEONG',
      title: null,
      suffix: null,
    },
    nationality: 'KR',
    expirationDate: '2024-06-16T00:00:00',
    number: 'M12345678',
    issuedDate: '2016-06-16T00:00:00',
    gender: 'Male',
    dateOfBirth: '1993-12-16T00:00:00',
    documentTypeText: 'P',
  },
  phoneNumber: null,
  onlineCheckInStatus: 'Applicable',
  failReason: null,
  failReasonText: '',
  addressKey: 'Qw--',
  onlineCheckInStatusText: '신청 가능',
};

export default {
  journeyKey:
    'WVB_IDU1MX4gfn5JQ05_MDgvMTEvMjAyMCAyMDowMH5CS0t_MDgvMTEvMjAyMCAyMzo1NX5_',
  passengers: [
    {
      passengerKey: 'MCFBRFQ-',
      name: {
        first: 'Daehee',
        middle: null,
        last: 'Jeong',
        title: null,
        suffix: null,
      },
      travelDocument: {
        documentTypeCode: 'P',
        passengerTravelDocumentKey: 'UCFLUiEg',
        birthCountry: 'KR',
        issuedByCode: 'KR',
        name: {
          first: 'DAEHEEADT',
          middle: null,
          last: 'JEONG',
          title: null,
          suffix: null,
        },
        nationality: 'KR',
        expirationDate: '2024-06-16T00:00:00',
        number: 'M12345678',
        issuedDate: '2016-06-16T00:00:00',
        gender: 'Male',
        dateOfBirth: '1993-12-16T00:00:00',
        documentTypeText: 'P',
      },
      phoneNumber: null,
      onlineCheckInStatus: 'Applicable',
      failReason: null,
      failReasonText: '',
      addressKey: 'Qw--',
      onlineCheckInStatusText: '신청 가능',
    },
    {
      passengerKey: 'MSFDSEQ-',
      name: {
        first: 'DaeheeChild',
        middle: null,
        last: 'Jeong',
        title: null,
        suffix: null,
      },
      travelDocument: {
        documentTypeCode: 'P',
        passengerTravelDocumentKey: 'UCFLUiEg',
        birthCountry: 'KR',
        issuedByCode: 'KR',
        name: {
          first: 'DAEHEECHILD',
          middle: null,
          last: 'JEONG',
          title: null,
          suffix: null,
        },
        nationality: 'KR',
        expirationDate: '2024-06-16T00:00:00',
        number: 'M12345678',
        issuedDate: '2016-06-16T00:00:00',
        gender: 'Male',
        dateOfBirth: '2013-12-16T00:00:00',
        documentTypeText: 'P',
      },
      phoneNumber: null,
      onlineCheckInStatus: 'Applicable',
      failReason: null,
      failReasonText: '',
      addressKey: 'Qw--',
      onlineCheckInStatusText: '신청 가능',
    },
    {
      passengerKey: 'MiFJTlM-',
      name: {
        first: 'DaeheeSeatInfant',
        middle: null,
        last: 'Jeong',
        title: null,
        suffix: null,
      },
      travelDocument: null,
      phoneNumber: null,
      onlineCheckInStatus: 'Applicable',
      failReason: null,
      failReasonText: '',
      addressKey: 'Qw--',
      onlineCheckInStatusText: '신청 가능',
    },
  ],
  countryCodeList: {
    suggestions: [
      {
        countryCode: 'KR',
        countryCode3C: 'KOR',
        defaultCurrencyCode: 'KRW',
        countryText: 'Korea, Republic of',
        countryTextKr: "대한민국",
        countryNumber: 82,
      },
      {
        countryCode: 'SG',
        countryCode3C: 'SGP',
        defaultCurrencyCode: 'USD',
        countryText: 'Singapore, Republic of',
        countryTextKr: "싱가포르",
        countryNumber: null,
      },
      {
        countryCode: 'TH',
        countryCode3C: 'THA',
        defaultCurrencyCode: 'USD',
        countryText: 'Thailand, Kingdom of',
        countryTextKr: "태국",
        countryNumber: null,
      },
      {
        countryCode: 'VN',
        countryCode3C: 'VNM',
        defaultCurrencyCode: 'USD',
        countryText: 'Vietnam',
        countryTextKr: "베트남",
        countryNumber: 84,
      },
    ],
    counties: [
      {
        countryCode: 'AD',
        countryCode3C: 'AND',
        defaultCurrencyCode: 'USD',
        countryText: 'Andorra',
        countryTextKr: '안도라',
        countryNumber: 376,
      },
      {
        countryCode: 'AE',
        countryCode3C: 'ARE',
        defaultCurrencyCode: 'USD',
        countryText: 'United Arab Emirates',
        countryTextKr: '아랍에미리트',
        countryNumber: 971,
      },
      {
        countryCode: 'AF',
        countryCode3C: 'AFG',
        defaultCurrencyCode: 'USD',
        countryText: 'Afghanistan',
        countryTextKr: '아프가니스탄',
        countryNumber: 93,
      },
      {
        countryCode: 'AG',
        countryCode3C: 'ATG',
        defaultCurrencyCode: 'USD',
        countryText: 'Antigua and Barbuda',
        countryTextKr: '앤티가 바부다',
        countryNumber: 1268,
      },
      {
        countryCode: 'AL',
        countryCode3C: 'ALB',
        defaultCurrencyCode: 'USD',
        countryText: 'Albania',
        countryTextKr: '알바니아',
        countryNumber: 355,
      },
      {
        countryCode: 'AM',
        countryCode3C: 'ARM',
        defaultCurrencyCode: 'USD',
        countryText: 'Armenia',
        countryTextKr: '아르메니아',
        countryNumber: 374,
      },
      {
        countryCode: 'AO',
        countryCode3C: 'AGO',
        defaultCurrencyCode: 'USD',
        countryText: 'Angola',
        countryTextKr: '앙골라',
        countryNumber: 244,
      },
      {
        countryCode: 'AR',
        countryCode3C: 'ARG',
        defaultCurrencyCode: 'USD',
        countryText: 'Argentina',
        countryTextKr: '아르헨티나',
        countryNumber: 54,
      },
      {
        countryCode: 'AT',
        countryCode3C: 'AUT',
        defaultCurrencyCode: 'USD',
        countryText: 'Austria',
        countryTextKr: '오스트리아',
        countryNumber: 43,
      },
      {
        countryCode: 'AU',
        countryCode3C: 'AUS',
        defaultCurrencyCode: 'USD',
        countryText: 'Australia',
        countryTextKr: '호주',
        countryNumber: 61,
      },
      {
        countryCode: 'AW',
        countryCode3C: 'ABW',
        defaultCurrencyCode: 'USD',
        countryText: 'Aruba',
        countryTextKr: '아루바',
        countryNumber: 297,
      },
      {
        countryCode: 'AZ',
        countryCode3C: 'AZE',
        defaultCurrencyCode: 'USD',
        countryText: 'Azerbaijan',
        countryTextKr: '아제르바이잔',
        countryNumber: 994,
      },
      {
        countryCode: 'BA',
        countryCode3C: 'BIH',
        defaultCurrencyCode: 'USD',
        countryText: 'Bosnia and Herzegovina',
        countryTextKr: '보스니아',
        countryNumber: 387,
      },
      {
        countryCode: 'BD',
        countryCode3C: 'BGD',
        defaultCurrencyCode: 'USD',
        countryText: 'Bangladesh',
        countryTextKr: '방글라데시',
        countryNumber: 880,
      },
      {
        countryCode: 'BE',
        countryCode3C: 'BEL',
        defaultCurrencyCode: 'USD',
        countryText: 'Belgium',
        countryTextKr: '벨기에',
        countryNumber: 32,
      },
      {
        countryCode: 'BF',
        countryCode3C: 'BFA',
        defaultCurrencyCode: 'USD',
        countryText: 'Burkina Faso',
        countryTextKr: '부르키나파소',
        countryNumber: 226,
      },
      {
        countryCode: 'BG',
        countryCode3C: 'BGR',
        defaultCurrencyCode: 'USD',
        countryText: 'Bulgaria',
        countryTextKr: '불가리아',
        countryNumber: 359,
      },
      {
        countryCode: 'BH',
        countryCode3C: 'BHR',
        defaultCurrencyCode: 'USD',
        countryText: 'Bahrain',
        countryTextKr: '바레인',
        countryNumber: 973,
      },
      {
        countryCode: 'BI',
        countryCode3C: 'BDI',
        defaultCurrencyCode: 'USD',
        countryText: 'Burundi',
        countryTextKr: '부룬디',
        countryNumber: 257,
      },
      {
        countryCode: 'BJ',
        countryCode3C: 'BEN',
        defaultCurrencyCode: 'USD',
        countryText: 'Benin',
        countryTextKr: '베냉',
        countryNumber: 229,
      },
      {
        countryCode: 'BN',
        countryCode3C: 'BRN',
        defaultCurrencyCode: 'USD',
        countryText: 'Brunei Darussalam',
        countryTextKr: '브루나이',
        countryNumber: 673,
      },
      {
        countryCode: 'BO',
        countryCode3C: 'BOL',
        defaultCurrencyCode: 'USD',
        countryText:
          'Bolivia, Plurinational State of Bolivia',
        countryTextKr: '볼리비아',
        countryNumber: 591,
      },
      {
        countryCode: 'BR',
        countryCode3C: 'BRA',
        defaultCurrencyCode: 'USD',
        countryText: 'Brazil',
        countryTextKr: '브라질',
        countryNumber: 55,
      },
      {
        countryCode: 'BT',
        countryCode3C: 'BTN',
        defaultCurrencyCode: 'USD',
        countryText: 'Bhutan',
        countryTextKr: '부탄',
        countryNumber: 975,
      },
      {
        countryCode: 'BV',
        countryCode3C: 'BVT',
        defaultCurrencyCode: 'USD',
        countryText: 'Bouvet Island',
        countryTextKr: '부베섬',
        countryNumber: 55,
      },
      {
        countryCode: 'BW',
        countryCode3C: 'BWA',
        defaultCurrencyCode: 'USD',
        countryText: 'Botswana',
        countryTextKr: '보츠와나',
        countryNumber: 267,
      },
      {
        countryCode: 'BY',
        countryCode3C: 'BLR',
        defaultCurrencyCode: 'USD',
        countryText: 'Belarus',
        countryTextKr: '벨라루스',
        countryNumber: 375,
      },
      {
        countryCode: 'BZ',
        countryCode3C: 'BLZ',
        defaultCurrencyCode: 'USD',
        countryText: 'Belize',
        countryTextKr: '벨리즈',
        countryNumber: 501,
      },
      {
        countryCode: 'CA',
        countryCode3C: 'CAN',
        defaultCurrencyCode: 'USD',
        countryText: 'Canada',
        countryTextKr: '캐나다',
        countryNumber: 1,
      },
      {
        countryCode: 'CC',
        countryCode3C: 'CCK',
        defaultCurrencyCode: 'USD',
        countryText: 'Cocos (Keeling) Islands',
        countryTextKr: '코코스 제도',
        countryNumber: 61,
      },
      {
        countryCode: 'CD',
        countryCode3C: 'COD',
        defaultCurrencyCode: 'USD',
        countryText:
          'Congo, The Democratic Republic of the',
        countryTextKr: '콩고민주공화국',
        countryNumber: 243,
      },
      {
        countryCode: 'CF',
        countryCode3C: 'CAF',
        defaultCurrencyCode: 'USD',
        countryText: 'Central African Republic',
        countryTextKr: '중앙아프리카공화국',
        countryNumber: 236,
      },
      {
        countryCode: 'CG',
        countryCode3C: 'COG',
        defaultCurrencyCode: 'USD',
        countryText: 'Congo',
        countryTextKr: '콩고',
        countryNumber: 242,
      },
      {
        countryCode: 'CH',
        countryCode3C: 'CHE',
        defaultCurrencyCode: 'USD',
        countryText: 'Switzerland',
        countryTextKr: '스위스',
        countryNumber: 41,
      },
      {
        countryCode: 'CI',
        countryCode3C: 'CIV',
        defaultCurrencyCode: 'USD',
        countryText: 'Cote dIvoire',
        countryTextKr: '아이보리 코스트',
        countryNumber: 225,
      },
      {
        countryCode: 'CK',
        countryCode3C: 'COK',
        defaultCurrencyCode: 'USD',
        countryText: 'Cook Islands',
        countryTextKr: '쿡 제도',
        countryNumber: 682,
      },
      {
        countryCode: 'CL',
        countryCode3C: 'CHL',
        defaultCurrencyCode: 'USD',
        countryText: 'Chile',
        countryTextKr: '칠레',
        countryNumber: 56,
      },
      {
        countryCode: 'CM',
        countryCode3C: 'CMR',
        defaultCurrencyCode: 'USD',
        countryText: 'Cameroon',
        countryTextKr: '카메룬',
        countryNumber: 237,
      },
      {
        countryCode: 'CN',
        countryCode3C: 'CHN',
        defaultCurrencyCode: 'USD',
        countryText: 'China',
        countryTextKr: '중국',
        countryNumber: 86,
      },
      {
        countryCode: 'CO',
        countryCode3C: 'COL',
        defaultCurrencyCode: 'USD',
        countryText: 'Colombia',
        countryTextKr: '콜롬비아',
        countryNumber: 57,
      },
      {
        countryCode: 'CR',
        countryCode3C: 'CRI',
        defaultCurrencyCode: 'USD',
        countryText: 'Costa Rica',
        countryTextKr: '코스타리카',
        countryNumber: 506,
      },
      {
        countryCode: 'CU',
        countryCode3C: 'CUB',
        defaultCurrencyCode: 'USD',
        countryText: 'Cuba',
        countryTextKr: '쿠바',
        countryNumber: 53,
      },
      {
        countryCode: 'CV',
        countryCode3C: 'CPV',
        defaultCurrencyCode: 'USD',
        countryText: 'Cape Verde',
        countryTextKr: '카보베르데',
        countryNumber: 238,
      },
      {
        countryCode: 'CX',
        countryCode3C: 'CXR',
        defaultCurrencyCode: 'USD',
        countryText: 'Christmas Island',
        countryTextKr: '',
        countryNumber: 61,
      },
      {
        countryCode: 'CY',
        countryCode3C: 'CYP',
        defaultCurrencyCode: 'USD',
        countryText: 'Cyprus',
        countryTextKr: '키프로스',
        countryNumber: 357,
      },
      {
        countryCode: 'CZ',
        countryCode3C: 'CZE',
        defaultCurrencyCode: 'USD',
        countryText: 'Czech Republic',
        countryTextKr: '체코 공화국',
        countryNumber: 420,
      },
      {
        countryCode: 'DE',
        countryCode3C: 'DEU',
        defaultCurrencyCode: 'USD',
        countryText: 'Germany',
        countryTextKr: '독일',
        countryNumber: 49,
      },
      {
        countryCode: 'DJ',
        countryCode3C: 'DJI',
        defaultCurrencyCode: 'USD',
        countryText: 'Djibouti',
        countryTextKr: '지부티',
        countryNumber: 253,
      },
      {
        countryCode: 'DK',
        countryCode3C: 'DNK',
        defaultCurrencyCode: 'USD',
        countryText: 'Denmark',
        countryTextKr: '덴마크',
        countryNumber: 45,
      },
      {
        countryCode: 'DZ',
        countryCode3C: 'DZA',
        defaultCurrencyCode: 'USD',
        countryText: 'Algeria',
        countryTextKr: '알제리',
        countryNumber: 213,
      },
      {
        countryCode: 'EC',
        countryCode3C: 'ECU',
        defaultCurrencyCode: 'USD',
        countryText: 'Ecuador',
        countryTextKr: '에콰도르',
        countryNumber: 593,
      },
      {
        countryCode: 'EE',
        countryCode3C: 'EST',
        defaultCurrencyCode: 'USD',
        countryText: 'Estonia',
        countryTextKr: '에스토니아',
        countryNumber: 372,
      },
      {
        countryCode: 'EG',
        countryCode3C: 'EGY',
        defaultCurrencyCode: 'USD',
        countryText: 'Egypt',
        countryTextKr: '이집트',
        countryNumber: 20,
      },
      {
        countryCode: 'EH',
        countryCode3C: 'ESH',
        defaultCurrencyCode: 'USD',
        countryText: 'Western Sahara',
        countryTextKr: ' 서사하라',
        countryNumber: 732,
      },
      {
        countryCode: 'ER',
        countryCode3C: 'ERI',
        defaultCurrencyCode: 'USD',
        countryText: 'Eritrea',
        countryTextKr: '에리트레아',
        countryNumber: 291,
      },
      {
        countryCode: 'ES',
        countryCode3C: 'ESP',
        defaultCurrencyCode: 'USD',
        countryText: 'Spain',
        countryTextKr: '스페인',
        countryNumber: 34,
      },
      {
        countryCode: 'ET',
        countryCode3C: 'ETH',
        defaultCurrencyCode: 'USD',
        countryText: 'Ethiopia',
        countryTextKr: '에티오피아',
        countryNumber: 251,
      },
      {
        countryCode: 'FI',
        countryCode3C: 'FIN',
        defaultCurrencyCode: 'USD',
        countryText: 'Finland',
        countryTextKr: '핀란드',
        countryNumber: 358,
      },
      {
        countryCode: 'FJ',
        countryCode3C: 'FJI',
        defaultCurrencyCode: 'USD',
        countryText: 'Fiji',
        countryTextKr: '피지',
        countryNumber: 679,
      },
      {
        countryCode: 'FK',
        countryCode3C: 'FLK',
        defaultCurrencyCode: 'USD',
        countryText: 'Falkland Islands (Malvinas)',
        countryTextKr: '포클랜드 제도',
        countryNumber: 500,
      },
      {
        countryCode: 'FM',
        countryCode3C: 'FSM',
        defaultCurrencyCode: 'USD',
        countryText: 'Micronesia, Federated States of',
        countryTextKr: '미크로네시아 연방국',
        countryNumber: 691,
      },
      {
        countryCode: 'FO',
        countryCode3C: 'FRO',
        defaultCurrencyCode: 'USD',
        countryText: 'Faroe Islands',
        countryTextKr: '페로 제도',
        countryNumber: 298,
      },
      {
        countryCode: 'FR',
        countryCode3C: 'FRA',
        defaultCurrencyCode: 'USD',
        countryText: 'France',
        countryTextKr: '프랑스',
        countryNumber: 33,
      },
      {
        countryCode: 'GA',
        countryCode3C: 'GAB',
        defaultCurrencyCode: 'USD',
        countryText: 'Gabon',
        countryTextKr: '가봉',
        countryNumber: 241,
      },
      {
        countryCode: 'GB',
        countryCode3C: 'GBR',
        defaultCurrencyCode: 'USD',
        countryText: 'United Kingdom',
        countryTextKr: '영국',
        countryNumber: 44,
      },
      {
        countryCode: 'GE',
        countryCode3C: 'GEO',
        defaultCurrencyCode: 'USD',
        countryText: 'Georgia',
        countryTextKr: '그루지야',
        countryNumber: 995,
      },
      {
        countryCode: 'GF',
        countryCode3C: 'GUF',
        defaultCurrencyCode: 'USD',
        countryText: 'French Guiana',
        countryTextKr: '프랑스령 기아나',
        countryNumber: 594,
      },
      {
        countryCode: 'GG',
        countryCode3C: 'GGY',
        defaultCurrencyCode: 'USD',
        countryText: 'Guernsey',
        countryTextKr: '건지',
        countryNumber: 44,
      },
      {
        countryCode: 'GH',
        countryCode3C: 'GHA',
        defaultCurrencyCode: 'USD',
        countryText: 'Ghana',
        countryTextKr: '가나',
        countryNumber: 233,
      },
      {
        countryCode: 'GI',
        countryCode3C: 'GIB',
        defaultCurrencyCode: 'USD',
        countryText: 'Gibraltar',
        countryTextKr: '지브롤터',
        countryNumber: 350,
      },
      {
        countryCode: 'GL',
        countryCode3C: 'GRL',
        defaultCurrencyCode: 'USD',
        countryText: 'Greenland',
        countryTextKr: '그린랜드',
        countryNumber: 299,
      },
      {
        countryCode: 'GM',
        countryCode3C: 'GMB',
        defaultCurrencyCode: 'USD',
        countryText: 'Gambia',
        countryTextKr: '감비아',
        countryNumber: 220,
      },
      {
        countryCode: 'GN',
        countryCode3C: 'GIN',
        defaultCurrencyCode: 'USD',
        countryText: 'Guinea',
        countryTextKr: '기니',
        countryNumber: 224,
      },
      {
        countryCode: 'GP',
        countryCode3C: 'GLP',
        defaultCurrencyCode: 'USD',
        countryText: 'Guadeloupe',
        countryTextKr: '과들루프',
        countryNumber: 590,
      },
      {
        countryCode: 'GQ',
        countryCode3C: 'GNQ',
        defaultCurrencyCode: 'USD',
        countryText: 'Equatorial Guinea',
        countryTextKr: '적도 기니',
        countryNumber: 240,
      },
      {
        countryCode: 'GR',
        countryCode3C: 'GRC',
        defaultCurrencyCode: 'USD',
        countryText: 'Greece',
        countryTextKr: '그리스',
        countryNumber: 30,
      },
      {
        countryCode: 'GS',
        countryCode3C: 'SGS',
        defaultCurrencyCode: 'USD',
        countryText:
          'South Georgia and the South Sandwich Islands',
        countryTextKr: '',
        countryNumber: 500,
      },
      {
        countryCode: 'GT',
        countryCode3C: 'GTM',
        defaultCurrencyCode: 'USD',
        countryText: 'Guatemala',
        countryTextKr: '과테말라',
        countryNumber: 502,
      },
      {
        countryCode: 'GW',
        countryCode3C: 'GNB',
        defaultCurrencyCode: 'USD',
        countryText: 'Guinea-Bissau',
        countryTextKr: '기니비사우',
        countryNumber: 245,
      },
      {
        countryCode: 'GY',
        countryCode3C: 'GUY',
        defaultCurrencyCode: 'USD',
        countryText: 'Guyana',
        countryTextKr: '가이아나',
        countryNumber: 592,
      },
      {
        countryCode: 'HK',
        countryCode3C: 'HKG',
        defaultCurrencyCode: 'USD',
        countryText: 'Hong Kong',
        countryTextKr: '홍콩',
        countryNumber: 852,
      },
      {
        countryCode: 'HM',
        countryCode3C: 'HMD',
        defaultCurrencyCode: 'USD',
        countryText: 'Heard Island and McDonald Islands',
        countryTextKr: '허드 맥도널드 제도',
        countryNumber: 672,
      },
      {
        countryCode: 'HN',
        countryCode3C: 'HND',
        defaultCurrencyCode: 'USD',
        countryText: 'Honduras',
        countryTextKr: '온두라스',
        countryNumber: 504,
      },
      {
        countryCode: 'HR',
        countryCode3C: 'HRV',
        defaultCurrencyCode: 'USD',
        countryText: 'Croatia',
        countryTextKr: '크로아티아',
        countryNumber: 385,
      },
      {
        countryCode: 'HT',
        countryCode3C: 'HTI',
        defaultCurrencyCode: 'USD',
        countryText: 'Haiti',
        countryTextKr: '아이티',
        countryNumber: 509,
      },
      {
        countryCode: 'HU',
        countryCode3C: 'HUN',
        defaultCurrencyCode: 'USD',
        countryText: 'Hungary',
        countryTextKr: '헝가리',
        countryNumber: 36,
      },
      {
        countryCode: 'ID',
        countryCode3C: 'IDN',
        defaultCurrencyCode: 'USD',
        countryText: 'Indonesia',
        countryTextKr: '인도네시아',
        countryNumber: 62,
      },
      {
        countryCode: 'IE',
        countryCode3C: 'IRL',
        defaultCurrencyCode: 'USD',
        countryText: 'Ireland',
        countryTextKr: '아일랜드 공화국',
        countryNumber: 353,
      },
      {
        countryCode: 'IL',
        countryCode3C: 'ISR',
        defaultCurrencyCode: 'USD',
        countryText: 'Israel',
        countryTextKr: '이스라엘',
        countryNumber: 972,
      },
      {
        countryCode: 'IM',
        countryCode3C: 'IMN',
        defaultCurrencyCode: 'USD',
        countryText: 'Isle of Man',
        countryTextKr: '맨섬',
        countryNumber: 44,
      },
      {
        countryCode: 'IN',
        countryCode3C: 'IND',
        defaultCurrencyCode: 'USD',
        countryText: 'India',
        countryTextKr: '인도',
        countryNumber: 91,
      },
      {
        countryCode: 'IO',
        countryCode3C: 'IOT',
        defaultCurrencyCode: 'USD',
        countryText: 'British Indian Ocean Territory',
        countryTextKr: '영국령 인도양 지역',
        countryNumber: 246,
      },
      {
        countryCode: 'IQ',
        countryCode3C: 'IRQ',
        defaultCurrencyCode: 'USD',
        countryText: 'Iraq',
        countryTextKr: '이라크',
        countryNumber: 964,
      },
      {
        countryCode: 'IR',
        countryCode3C: 'IRN',
        defaultCurrencyCode: 'USD',
        countryText: 'Iran, Islamic Republic of',
        countryTextKr: '이란',
        countryNumber: 98,
      },
      {
        countryCode: 'IS',
        countryCode3C: 'ISL',
        defaultCurrencyCode: 'USD',
        countryText: 'Iceland',
        countryTextKr: '아이슬란드',
        countryNumber: 354,
      },
      {
        countryCode: 'IT',
        countryCode3C: 'ITA',
        defaultCurrencyCode: 'USD',
        countryText: 'Italy',
        countryTextKr: '이탈리아',
        countryNumber: 39,
      },
      {
        countryCode: 'JE',
        countryCode3C: 'JEY',
        defaultCurrencyCode: 'USD',
        countryText: 'Jersey',
        countryTextKr: '저지',
        countryNumber: 44,
      },
      {
        countryCode: 'JO',
        countryCode3C: 'JOR',
        defaultCurrencyCode: 'USD',
        countryText: 'Jordan',
        countryTextKr: '요르단',
        countryNumber: 962,
      },
      {
        countryCode: 'JP',
        countryCode3C: 'JPN',
        defaultCurrencyCode: 'USD',
        countryText: 'Japan',
        countryTextKr: '일본',
        countryNumber: 81,
      },
      {
        countryCode: 'KE',
        countryCode3C: 'KEN',
        defaultCurrencyCode: 'USD',
        countryText: 'Kenya',
        countryTextKr: '케냐',
        countryNumber: 254,
      },
      {
        countryCode: 'KG',
        countryCode3C: 'KGZ',
        defaultCurrencyCode: 'USD',
        countryText: 'Kyrgyzstan',
        countryTextKr: '키르기스스탄',
        countryNumber: 996,
      },
      {
        countryCode: 'KH',
        countryCode3C: 'KHM',
        defaultCurrencyCode: 'USD',
        countryText: 'Cambodia',
        countryTextKr: '캄보디아',
        countryNumber: 855,
      },
      {
        countryCode: 'KI',
        countryCode3C: 'KIR',
        defaultCurrencyCode: 'USD',
        countryText: 'Kiribati',
        countryTextKr: '키리바시',
        countryNumber: 686,
      },
      {
        countryCode: 'KM',
        countryCode3C: 'COM',
        defaultCurrencyCode: 'USD',
        countryText: 'Comoros',
        countryTextKr: '코모로',
        countryNumber: 269,
      },
      {
        countryCode: 'KR',
        countryCode3C: 'KOR',
        defaultCurrencyCode: 'KRW',
        countryText: 'Korea, Republic of',
        countryTextKr: '대한민국',
        countryNumber: 82,
      },
      {
        countryCode: 'KW',
        countryCode3C: 'KWT',
        defaultCurrencyCode: 'USD',
        countryText: 'Kuwait',
        countryTextKr: '쿠웨이트',
        countryNumber: 965,
      },
      {
        countryCode: 'KY',
        countryCode3C: 'CYM',
        defaultCurrencyCode: 'USD',
        countryText: 'Cayman Islands',
        countryTextKr: '케이맨 제도',
        countryNumber: 1345,
      },
      {
        countryCode: 'KZ',
        countryCode3C: 'KAZ',
        defaultCurrencyCode: 'USD',
        countryText: 'Kazakhstan',
        countryTextKr: '카자흐스탄',
        countryNumber: 7,
      },
      {
        countryCode: 'LA',
        countryCode3C: 'LAO',
        defaultCurrencyCode: 'USD',
        countryText: 'Lao Peoples Democratic Republic',
        countryTextKr: '라오스',
        countryNumber: 856,
      },
      {
        countryCode: 'LB',
        countryCode3C: 'LBN',
        defaultCurrencyCode: 'USD',
        countryText: 'Lebanon',
        countryTextKr: '레바논',
        countryNumber: 961,
      },
      {
        countryCode: 'LI',
        countryCode3C: 'LIE',
        defaultCurrencyCode: 'USD',
        countryText: 'Liechtenstein',
        countryTextKr: '리히텐슈타인',
        countryNumber: 423,
      },
      {
        countryCode: 'LK',
        countryCode3C: 'LKA',
        defaultCurrencyCode: 'USD',
        countryText: 'Sri Lanka',
        countryTextKr: '스리랑카',
        countryNumber: 94,
      },
      {
        countryCode: 'LR',
        countryCode3C: 'LBR',
        defaultCurrencyCode: 'USD',
        countryText: 'Liberia',
        countryTextKr: '라이베리아',
        countryNumber: 231,
      },
      {
        countryCode: 'LS',
        countryCode3C: 'LSO',
        defaultCurrencyCode: 'USD',
        countryText: 'Lesotho',
        countryTextKr: '레소토',
        countryNumber: 266,
      },
      {
        countryCode: 'LT',
        countryCode3C: 'LTU',
        defaultCurrencyCode: 'USD',
        countryText: 'Lithuania',
        countryTextKr: '리투아니아',
        countryNumber: 370,
      },
      {
        countryCode: 'LU',
        countryCode3C: 'LUX',
        defaultCurrencyCode: 'USD',
        countryText: 'Luxembourg',
        countryTextKr: '룩셈부르크',
        countryNumber: 352,
      },
      {
        countryCode: 'LV',
        countryCode3C: 'LVA',
        defaultCurrencyCode: 'USD',
        countryText: 'Latvia',
        countryTextKr: '라트비아',
        countryNumber: 371,
      },
      {
        countryCode: 'LY',
        countryCode3C: 'LBY',
        defaultCurrencyCode: 'USD',
        countryText: 'Libyan Arab Jamahiriya',
        countryTextKr: '리비아',
        countryNumber: 218,
      },
      {
        countryCode: 'MA',
        countryCode3C: 'MAR',
        defaultCurrencyCode: 'USD',
        countryText: 'Morocco',
        countryTextKr: '모로코',
        countryNumber: 212,
      },
      {
        countryCode: 'MC',
        countryCode3C: 'MCO',
        defaultCurrencyCode: 'USD',
        countryText: 'Monaco',
        countryTextKr: '모나코',
        countryNumber: 377,
      },
      {
        countryCode: 'MD',
        countryCode3C: 'MDA',
        defaultCurrencyCode: 'USD',
        countryText: 'Moldova, Republic of',
        countryTextKr: '몰도바',
        countryNumber: 373,
      },
      {
        countryCode: 'ME',
        countryCode3C: 'MNE',
        defaultCurrencyCode: 'USD',
        countryText: 'Montenegro',
        countryTextKr: '몬테네그로',
        countryNumber: 382,
      },
      {
        countryCode: 'MG',
        countryCode3C: 'MDG',
        defaultCurrencyCode: 'USD',
        countryText: 'Madagascar',
        countryTextKr: '마다가스카르',
        countryNumber: 261,
      },
      {
        countryCode: 'MH',
        countryCode3C: 'MHL',
        defaultCurrencyCode: 'USD',
        countryText: 'Marshall Islands',
        countryTextKr: '마셜 제도',
        countryNumber: 692,
      },
      {
        countryCode: 'MK',
        countryCode3C: 'MKD',
        defaultCurrencyCode: 'USD',
        countryText:
          'Macedonia, The Former Yugoslav Republic of',
        countryTextKr: '마케도니아(FYROM)',
        countryNumber: 389,
      },
      {
        countryCode: 'ML',
        countryCode3C: 'MLI',
        defaultCurrencyCode: 'USD',
        countryText: 'Mali',
        countryTextKr: '말리',
        countryNumber: 223,
      },
      {
        countryCode: 'MM',
        countryCode3C: 'MMR',
        defaultCurrencyCode: 'USD',
        countryText: 'Myanmar',
        countryTextKr: '',
        countryNumber: 95,
      },
      {
        countryCode: 'MN',
        countryCode3C: 'MNG',
        defaultCurrencyCode: 'USD',
        countryText: 'Mongolia',
        countryTextKr: '몽골',
        countryNumber: 976,
      },
      {
        countryCode: 'MO',
        countryCode3C: 'MAC',
        defaultCurrencyCode: 'USD',
        countryText: 'Macao',
        countryTextKr: '마카오',
        countryNumber: 853,
      },
      {
        countryCode: 'MQ',
        countryCode3C: 'MTQ',
        defaultCurrencyCode: 'USD',
        countryText: 'Martinique',
        countryTextKr: '마르티니크',
        countryNumber: 596,
      },
      {
        countryCode: 'MR',
        countryCode3C: 'MRT',
        defaultCurrencyCode: 'USD',
        countryText: 'Mauritania',
        countryTextKr: '모리타니',
        countryNumber: 222,
      },
      {
        countryCode: 'MS',
        countryCode3C: 'MSR',
        defaultCurrencyCode: 'USD',
        countryText: 'Montserrat',
        countryTextKr: '몬트세라트',
        countryNumber: 1664,
      },
      {
        countryCode: 'MT',
        countryCode3C: 'MLT',
        defaultCurrencyCode: 'USD',
        countryText: 'Malta',
        countryTextKr: '몰타',
        countryNumber: 356,
      },
      {
        countryCode: 'MU',
        countryCode3C: 'MUS',
        defaultCurrencyCode: 'USD',
        countryText: 'Mauritius',
        countryTextKr: '모리셔스',
        countryNumber: 230,
      },
      {
        countryCode: 'MV',
        countryCode3C: 'MDV',
        defaultCurrencyCode: 'USD',
        countryText: 'Maldives',
        countryTextKr: '몰디브',
        countryNumber: 960,
      },
      {
        countryCode: 'MW',
        countryCode3C: 'MWI',
        defaultCurrencyCode: 'USD',
        countryText: 'Malawi',
        countryTextKr: '말라위',
        countryNumber: 265,
      },
      {
        countryCode: 'MX',
        countryCode3C: 'MEX',
        defaultCurrencyCode: 'USD',
        countryText: 'Mexico',
        countryTextKr: '멕시코',
        countryNumber: 52,
      },
      {
        countryCode: 'MY',
        countryCode3C: 'MYS',
        defaultCurrencyCode: 'USD',
        countryText: 'Malaysia',
        countryTextKr: '말레이시아',
        countryNumber: 60,
      },
      {
        countryCode: 'MZ',
        countryCode3C: 'MOZ',
        defaultCurrencyCode: 'USD',
        countryText: 'Mozambique',
        countryTextKr: '모잠비크',
        countryNumber: 258,
      },
      {
        countryCode: 'NA',
        countryCode3C: 'NAM',
        defaultCurrencyCode: 'USD',
        countryText: 'Namibia',
        countryTextKr: '나미비아',
        countryNumber: 264,
      },
      {
        countryCode: 'NC',
        countryCode3C: 'NCL',
        defaultCurrencyCode: 'USD',
        countryText: 'New Caledonia',
        countryTextKr: '뉴칼레도니아',
        countryNumber: 687,
      },
      {
        countryCode: 'NE',
        countryCode3C: 'NER',
        defaultCurrencyCode: 'USD',
        countryText: 'Niger',
        countryTextKr: '니제르',
        countryNumber: 227,
      },
      {
        countryCode: 'NF',
        countryCode3C: 'NFK',
        defaultCurrencyCode: 'USD',
        countryText: 'Norfolk Island',
        countryTextKr: '노퍽 섬',
        countryNumber: 672,
      },
      {
        countryCode: 'NG',
        countryCode3C: 'NGA',
        defaultCurrencyCode: 'USD',
        countryText: 'Nigeria',
        countryTextKr: '나이지리아',
        countryNumber: 234,
      },
      {
        countryCode: 'NI',
        countryCode3C: 'NIC',
        defaultCurrencyCode: 'USD',
        countryText: 'Nicaragua',
        countryTextKr: '니카라과',
        countryNumber: 505,
      },
      {
        countryCode: 'NL',
        countryCode3C: 'NLD',
        defaultCurrencyCode: 'USD',
        countryText: 'Netherlands',
        countryTextKr: '네덜란드',
        countryNumber: 31,
      },
      {
        countryCode: 'NO',
        countryCode3C: 'NOR',
        defaultCurrencyCode: 'USD',
        countryText: 'Norway',
        countryTextKr: '노르웨이',
        countryNumber: 47,
      },
      {
        countryCode: 'NP',
        countryCode3C: 'NPL',
        defaultCurrencyCode: 'USD',
        countryText: 'Nepal',
        countryTextKr: '네팔',
        countryNumber: 977,
      },
      {
        countryCode: 'NR',
        countryCode3C: 'NRU',
        defaultCurrencyCode: 'USD',
        countryText: 'Nauru',
        countryTextKr: '',
        countryNumber: 674,
      },
      {
        countryCode: 'NU',
        countryCode3C: 'NIU',
        defaultCurrencyCode: 'USD',
        countryText: 'Niue',
        countryTextKr: '',
        countryNumber: 683,
      },
      {
        countryCode: 'NZ',
        countryCode3C: 'NZL',
        defaultCurrencyCode: 'USD',
        countryText: 'New Zealand',
        countryTextKr: '뉴질랜드',
        countryNumber: 64,
      },
      {
        countryCode: 'OM',
        countryCode3C: 'OMN',
        defaultCurrencyCode: 'USD',
        countryText: 'Oman',
        countryTextKr: '오만',
        countryNumber: 968,
      },
      {
        countryCode: 'PA',
        countryCode3C: 'PAN',
        defaultCurrencyCode: 'USD',
        countryText: 'Panama',
        countryTextKr: '파나마',
        countryNumber: 507,
      },
      {
        countryCode: 'PE',
        countryCode3C: 'PER',
        defaultCurrencyCode: 'USD',
        countryText: 'Peru',
        countryTextKr: '페루',
        countryNumber: 51,
      },
      {
        countryCode: 'PF',
        countryCode3C: 'PYF',
        defaultCurrencyCode: 'USD',
        countryText: 'French Polynesia',
        countryTextKr: '프랑스령 폴리네시아',
        countryNumber: 689,
      },
      {
        countryCode: 'PG',
        countryCode3C: 'PNG',
        defaultCurrencyCode: 'USD',
        countryText: 'Papua New Guinea',
        countryTextKr: '파푸아뉴기니',
        countryNumber: 675,
      },
      {
        countryCode: 'PH',
        countryCode3C: 'PHL',
        defaultCurrencyCode: 'USD',
        countryText: 'Philippines',
        countryTextKr: '필리핀',
        countryNumber: 63,
      },
      {
        countryCode: 'PK',
        countryCode3C: 'PAK',
        defaultCurrencyCode: 'USD',
        countryText: 'Pakistan',
        countryTextKr: '파키스탄',
        countryNumber: 92,
      },
      {
        countryCode: 'PL',
        countryCode3C: 'POL',
        defaultCurrencyCode: 'USD',
        countryText: 'Poland',
        countryTextKr: '폴란드',
        countryNumber: 48,
      },
      {
        countryCode: 'PM',
        countryCode3C: 'SPM',
        defaultCurrencyCode: 'USD',
        countryText: 'Saint Pierre and Miquelon',
        countryTextKr: '',
        countryNumber: 508,
      },
      {
        countryCode: 'PN',
        countryCode3C: 'PCN',
        defaultCurrencyCode: 'USD',
        countryText: 'Pitcairn',
        countryTextKr: '',
        countryNumber: 870,
      },
      {
        countryCode: 'PS',
        countryCode3C: 'PSE',
        defaultCurrencyCode: 'USD',
        countryText: 'Palestinian Territory, Occupied',
        countryTextKr: '',
        countryNumber: 970,
      },
      {
        countryCode: 'PT',
        countryCode3C: 'PRT',
        defaultCurrencyCode: 'USD',
        countryText: 'Portugal',
        countryTextKr: '포르투갈',
        countryNumber: 351,
      },
      {
        countryCode: 'PW',
        countryCode3C: 'PLW',
        defaultCurrencyCode: 'USD',
        countryText: 'Palau',
        countryTextKr: '팔라우',
        countryNumber: 680,
      },
      {
        countryCode: 'PY',
        countryCode3C: 'PRY',
        defaultCurrencyCode: 'USD',
        countryText: 'Paraguay',
        countryTextKr: '파라과이',
        countryNumber: 595,
      },
      {
        countryCode: 'QA',
        countryCode3C: 'QAT',
        defaultCurrencyCode: 'USD',
        countryText: 'Qatar',
        countryTextKr: '카타르',
        countryNumber: 974,
      },
      {
        countryCode: 'RE',
        countryCode3C: 'REU',
        defaultCurrencyCode: 'USD',
        countryText: 'Réunion',
        countryTextKr: '레위니옹',
        countryNumber: 262,
      },
      {
        countryCode: 'RO',
        countryCode3C: 'ROU',
        defaultCurrencyCode: 'USD',
        countryText: 'Romania',
        countryTextKr: '루마니아',
        countryNumber: 40,
      },
      {
        countryCode: 'RS',
        countryCode3C: 'SRB',
        defaultCurrencyCode: 'USD',
        countryText: 'Serbia',
        countryTextKr: '세르비아',
        countryNumber: 381,
      },
      {
        countryCode: 'RU',
        countryCode3C: 'RUS',
        defaultCurrencyCode: 'USD',
        countryText: 'Russia',
        countryTextKr: '러시아',
        countryNumber: 7,
      },
      {
        countryCode: 'RW',
        countryCode3C: 'RWA',
        defaultCurrencyCode: 'USD',
        countryText: 'Rwanda',
        countryTextKr: '르완다',
        countryNumber: 250,
      },
      {
        countryCode: 'SA',
        countryCode3C: 'SAU',
        defaultCurrencyCode: 'USD',
        countryText: 'Saudi Arabia',
        countryTextKr: '사우디아라비아',
        countryNumber: 966,
      },
      {
        countryCode: 'SB',
        countryCode3C: 'SLB',
        defaultCurrencyCode: 'USD',
        countryText: 'Solomon Islands',
        countryTextKr: '솔로몬 제도',
        countryNumber: 677,
      },
      {
        countryCode: 'SC',
        countryCode3C: 'SYC',
        defaultCurrencyCode: 'USD',
        countryText: 'Seychelles',
        countryTextKr: '세이셸',
        countryNumber: 248,
      },
      {
        countryCode: 'SD',
        countryCode3C: 'SDN',
        defaultCurrencyCode: 'USD',
        countryText: 'Sudan',
        countryTextKr: '',
        countryNumber: 249,
      },
      {
        countryCode: 'SE',
        countryCode3C: 'SWE',
        defaultCurrencyCode: 'USD',
        countryText: 'Sweden',
        countryTextKr: '스웨덴',
        countryNumber: 46,
      },
      {
        countryCode: 'SG',
        countryCode3C: 'SGP',
        defaultCurrencyCode: 'USD',
        countryText: 'Singapore',
        countryTextKr: '싱가포르',
        countryNumber: 65,
      },
      {
        countryCode: 'SH',
        countryCode3C: 'SHN',
        defaultCurrencyCode: 'USD',
        countryText:
          'Saint Helena, Ascension and Tristan Da Cunha',
        countryTextKr: '',
        countryNumber: 290,
      },
      {
        countryCode: 'SI',
        countryCode3C: 'SVN',
        defaultCurrencyCode: 'USD',
        countryText: 'Slovenia',
        countryTextKr: '슬로베니아',
        countryNumber: 386,
      },
      {
        countryCode: 'SJ',
        countryCode3C: 'SJM',
        defaultCurrencyCode: 'USD',
        countryText: 'Svalbard and Jan Mayen',
        countryTextKr: '',
        countryNumber: 47,
      },
      {
        countryCode: 'SK',
        countryCode3C: 'SVK',
        defaultCurrencyCode: 'USD',
        countryText: 'Slovakia',
        countryTextKr: '슬로바키아',
        countryNumber: 421,
      },
      {
        countryCode: 'SL',
        countryCode3C: 'SLE',
        defaultCurrencyCode: 'USD',
        countryText: 'Sierra Leone',
        countryTextKr: '시에라리온',
        countryNumber: 232,
      },
      {
        countryCode: 'SM',
        countryCode3C: 'SMR',
        defaultCurrencyCode: 'USD',
        countryText: 'San Marino',
        countryTextKr: '산마리노',
        countryNumber: 378,
      },
      {
        countryCode: 'SN',
        countryCode3C: 'SEN',
        defaultCurrencyCode: 'USD',
        countryText: 'Senegal',
        countryTextKr: '세네갈',
        countryNumber: 221,
      },
      {
        countryCode: 'SO',
        countryCode3C: 'SOM',
        defaultCurrencyCode: 'USD',
        countryText: 'Somalia',
        countryTextKr: '',
        countryNumber: 252,
      },
      {
        countryCode: 'SR',
        countryCode3C: 'SUR',
        defaultCurrencyCode: 'USD',
        countryText: 'Suriname',
        countryTextKr: '수리남',
        countryNumber: 597,
      },
      {
        countryCode: 'ST',
        countryCode3C: 'STP',
        defaultCurrencyCode: 'USD',
        countryText: 'Sao Tome and Principe',
        countryTextKr: '상투메프린시페',
        countryNumber: 239,
      },
      {
        countryCode: 'SV',
        countryCode3C: 'SLV',
        defaultCurrencyCode: 'USD',
        countryText: 'El Salvador',
        countryTextKr: '엘살바도르',
        countryNumber: 503,
      },
      {
        countryCode: 'SY',
        countryCode3C: 'SYR',
        defaultCurrencyCode: 'USD',
        countryText: 'Syrian Arab Republic',
        countryTextKr: '쌩마뗑 및 세인트마틴',
        countryNumber: 963,
      },
      {
        countryCode: 'SZ',
        countryCode3C: 'SWZ',
        defaultCurrencyCode: 'USD',
        countryText: 'Swaziland',
        countryTextKr: '스와질랜드',
        countryNumber: 268,
      },
      {
        countryCode: 'TD',
        countryCode3C: 'TCD',
        defaultCurrencyCode: 'USD',
        countryText: 'Chad',
        countryTextKr: '차드',
        countryNumber: 235,
      },
      {
        countryCode: 'TF',
        countryCode3C: 'ATF',
        defaultCurrencyCode: 'USD',
        countryText: 'French Southern and Antarctic Lands',
        countryTextKr: '',
        countryNumber: 262,
      },
      {
        countryCode: 'TG',
        countryCode3C: 'TGO',
        defaultCurrencyCode: 'USD',
        countryText: 'Togo',
        countryTextKr: '토고',
        countryNumber: 228,
      },
      {
        countryCode: 'TH',
        countryCode3C: 'THA',
        defaultCurrencyCode: 'USD',
        countryText: 'Thailand',
        countryTextKr: '태국',
        countryNumber: 66,
      },
      {
        countryCode: 'TJ',
        countryCode3C: 'TJK',
        defaultCurrencyCode: 'USD',
        countryText: 'Tajikistan',
        countryTextKr: '타지키스탄',
        countryNumber: 992,
      },
      {
        countryCode: 'TK',
        countryCode3C: 'TKL',
        defaultCurrencyCode: 'USD',
        countryText: 'Tokelau',
        countryTextKr: '',
        countryNumber: 690,
      },
      {
        countryCode: 'TL',
        countryCode3C: 'TLS',
        defaultCurrencyCode: 'USD',
        countryText: 'Timor-Leste',
        countryTextKr: '동티모르',
        countryNumber: 670,
      },
      {
        countryCode: 'TM',
        countryCode3C: 'TKM',
        defaultCurrencyCode: 'USD',
        countryText: 'Turkmenistan',
        countryTextKr: '투르크메니스탄',
        countryNumber: 993,
      },
      {
        countryCode: 'TN',
        countryCode3C: 'TUN',
        defaultCurrencyCode: 'USD',
        countryText: 'Tunisia',
        countryTextKr: '튀니지',
        countryNumber: 216,
      },
      {
        countryCode: 'TO',
        countryCode3C: 'TON',
        defaultCurrencyCode: 'USD',
        countryText: 'Tonga',
        countryTextKr: '통가',
        countryNumber: 676,
      },
      {
        countryCode: 'TR',
        countryCode3C: 'TUR',
        defaultCurrencyCode: 'USD',
        countryText: 'Turkey',
        countryTextKr: '터키',
        countryNumber: 90,
      },
      {
        countryCode: 'TV',
        countryCode3C: 'TUV',
        defaultCurrencyCode: 'USD',
        countryText: 'Tuvalu',
        countryTextKr: '투발루',
        countryNumber: 688,
      },
      {
        countryCode: 'TW',
        countryCode3C: 'TWN',
        defaultCurrencyCode: 'USD',
        countryText: 'Taiwan',
        countryTextKr: '대만',
        countryNumber: 886,
      },
      {
        countryCode: 'TZ',
        countryCode3C: 'TZA',
        defaultCurrencyCode: 'USD',
        countryText: 'Tanzania, United Republic of',
        countryTextKr: '탄자니아',
        countryNumber: 255,
      },
      {
        countryCode: 'UA',
        countryCode3C: 'UKR',
        defaultCurrencyCode: 'USD',
        countryText: 'Ukraine',
        countryTextKr: '우크라이나',
        countryNumber: 380,
      },
      {
        countryCode: 'UG',
        countryCode3C: 'UGA',
        defaultCurrencyCode: 'USD',
        countryText: 'Uganda',
        countryTextKr: '우간다',
        countryNumber: 256,
      },
      {
        countryCode: 'UM',
        countryCode3C: 'UMI',
        defaultCurrencyCode: 'USD',
        countryText: 'United States Minor Outlying Islands',
        countryTextKr: '',
        countryNumber: 1581,
      },
      {
        countryCode: 'US',
        countryCode3C: 'USA',
        defaultCurrencyCode: 'USD',
        countryText: 'United States',
        countryTextKr: '미국',
        countryNumber: 1,
      },
      {
        countryCode: 'UY',
        countryCode3C: 'URY',
        defaultCurrencyCode: 'USD',
        countryText: 'Uruguay',
        countryTextKr: '우루과이',
        countryNumber: 598,
      },
      {
        countryCode: 'UZ',
        countryCode3C: 'UZB',
        defaultCurrencyCode: 'USD',
        countryText: 'Uzbekistan',
        countryTextKr: '우즈베키스탄',
        countryNumber: 998,
      },
      {
        countryCode: 'VA',
        countryCode3C: 'VAT',
        defaultCurrencyCode: 'USD',
        countryText: 'Holy See (Vatican City State)',
        countryTextKr: '바티칸 시국',
        countryNumber: 379,
      },
      {
        countryCode: 'VE',
        countryCode3C: 'VEN',
        defaultCurrencyCode: 'USD',
        countryText: 'Venezuela, Bolivarian Republic of',
        countryTextKr: '베네수엘라',
        countryNumber: 58,
      },
      {
        countryCode: 'VN',
        countryCode3C: 'VNM',
        defaultCurrencyCode: 'USD',
        countryText: 'Viet Nam',
        countryTextKr: '베트남',
        countryNumber: 84,
      },
      {
        countryCode: 'VU',
        countryCode3C: 'VUT',
        defaultCurrencyCode: 'USD',
        countryText: 'Vanuatu',
        countryTextKr: '바누아투',
        countryNumber: 678,
      },
      {
        countryCode: 'WF',
        countryCode3C: 'WLF',
        defaultCurrencyCode: 'USD',
        countryText: 'Wallis and Futuna',
        countryTextKr: '월리스 푸투나 제도',
        countryNumber: 681,
      },
      {
        countryCode: 'WS',
        countryCode3C: 'WSM',
        defaultCurrencyCode: 'USD',
        countryText: 'Samoa',
        countryTextKr: '사모아',
        countryNumber: 685,
      },
      {
        countryCode: 'YE',
        countryCode3C: 'YEM',
        defaultCurrencyCode: 'USD',
        countryText: 'Yemen',
        countryTextKr: '예멘',
        countryNumber: 967,
      },
      {
        countryCode: 'YT',
        countryCode3C: 'MYT',
        defaultCurrencyCode: 'USD',
        countryText: 'Mayotte',
        countryTextKr: '마요트',
        countryNumber: 262,
      },
      {
        countryCode: 'ZA',
        countryCode3C: 'ZAF',
        defaultCurrencyCode: 'USD',
        countryText: 'South Africa',
        countryTextKr: '남아프리카',
        countryNumber: 27,
      },
      {
        countryCode: 'ZM',
        countryCode3C: 'ZMB',
        defaultCurrencyCode: 'USD',
        countryText: 'Zambia',
        countryTextKr: '잠비아',
        countryNumber: 260,
      },
      {
        countryCode: 'ZW',
        countryCode3C: 'ZWE',
        defaultCurrencyCode: 'USD',
        countryText: 'Zimbabwe',
        countryTextKr: '짐바브웨',
        countryNumber: 263,
      },
    ],
  },
};
