export const pointsHistory = [
  {
    id: 1,
    transactionDate: '2020-08-05T05:54:17Z',
    type: 'Earn',
    amount: 1000,
    status: 'Confirmed',
    statusText: 'Confirmed',
    typeText: 'Earn',
    summaryText: '적립했습니다.',
  },
  {
    id: 2,
    transactionDate: '2020-08-05T05:54:17Z',
    type: 'Buy',
    amount: 1000,
    status: 'Confirmed',
    statusText: 'Confirmed',
    typeText: 'Buy',
    summaryText: '구매했습니다.',
  },
  {
    id: 3,
    transactionDate: '2020-08-05T05:54:17Z',
    type: 'Expired',
    amount: 1000,
    status: 'Confirmed',
    statusText: 'Confirmed',
    typeText: 'Extinction',
    summaryText: '소멸했습니다.',
  },
  {
    id: 4,
    transactionDate: '2020-08-05T05:54:17Z',
    type: 'Transfer',
    amount: 1000,
    status: 'Confirmed',
    statusText: 'Confirmed',
    typeText: 'Transfer',
    summaryText: '전송했습니다.',
  },
  {
    id: 5,
    transactionDate: '2020-08-05T05:54:17Z',
    type: 'Receive',
    amount: 1000,
    status: 'Confirmed',
    statusText: 'Confirmed',
    typeText: 'Receive',
    summaryText: '수신했습니다.',
  },
  {
    id: 6,
    transactionDate: '2020-08-05T05:54:17Z',
    type: 'Refund',
    amount: 1000,
    status: 'Confirmed',
    statusText: 'Confirmed',
    typeText: 'Refund',
    summaryText: '환불했습니다.',
  },
  {
    id: 7,
    transactionDate: '2020-08-05T05:54:17Z',
    type: 'Refund',
    amount: 1000,
    status: 'Confirmed',
    statusText: 'Confirmed',
    typeText: 'Refund',
    summaryText: '환불했습니다.',
  },
  {
    id: 8,
    transactionDate: '2020-08-05T05:54:17Z',
    type: 'Refund',
    amount: 1000,
    status: 'Confirmed',
    statusText: 'Confirmed',
    typeText: 'Refund',
    summaryText: '환불했습니다.',
  },
  {
    id: 9,
    transactionDate: '2020-08-05T05:54:17Z',
    type: 'Refund',
    amount: 1000,
    status: 'Confirmed',
    statusText: 'Confirmed',
    typeText: 'Refund',
    summaryText: '환불했습니다.',
  },
  {
    id: 10,
    transactionDate: '2020-08-05T05:54:17Z',
    type: 'Refund',
    amount: 1000,
    status: 'Confirmed',
    statusText: 'Confirmed',
    typeText: 'Refund',
    summaryText: '환불했습니다.',
  },
  {
    id: 11,
    transactionDate: '2020-08-05T05:54:17Z',
    type: 'Refund',
    amount: 1000,
    status: 'Confirmed',
    statusText: 'Confirmed',
    typeText: 'Refund',
    summaryText: '환불했습니다.',
  },
  {
    id: 12,
    transactionDate: '2020-08-05T05:54:17Z',
    type: 'Transfer',
    amount: 1000,
    status: 'Confirmed',
    statusText: 'Confirmed',
    typeText: 'Transfer',
    summaryText: '전송했습니다.',
  },
];

export const caution = {
  title: '포인트 유의사항',
  body: [
    '적립 금액은 각종 프로모션, 쿠폰 적용 후의 항공권 결제 금액만을 기준으로 하며 유류할증료, 공항사용료, 세금, 부가서비스 결제 금액은 적립에서 제외됩니다.',
    '포인트로 구매한 항공권, 포인트로 승급한 좌석처럼 포인트로 결제한 금액에 대해서는 포인트가 적립되지 않습니다.',
    '이벤트, 특가 항공권 등 포인트 적립이 되지 않는 클래스가 존재합니다. 클래스 선택 단계에서 안내하고 있으며 구매 전 확인이 필요합니다.',
    '실제 탑승 후 n영업일 안에 탑승자 본인 명의의 계정으로 적립되며 탑승하지 않았을 경우 포인트는 적립되지 않습니다.',
    '왕복 여정 탑승 시 가는 편 여정에 탑승 한 뒤 적립 인정 결제 금액의 50%가 적립되며 오는 편 여정에 탑승 한 뒤에 나머지 50%가 적립됩니다.',
    '현장에서 좌석 업그레이드를 현금, 카드 등으로 결제할 경우 업그레이드 가격에 대한 포인트도 적립됩니다.',
    '좌석을 점유하지 않는 유아(0~2세)용 항공권은 포인트가 적립되지 않습니다.',
    '좌석을 점유하는 유아 및 소아(24개월~12세)는 포인트 적립 대신 함께 예약한 성인에게 다음 예약 시 사용할 수 있는 할인 쿠폰을 제공합니다. 소아와 함께 탑승해야만 사용할 수 있으며 항공권 결제 금액에 따라 30만원 미만 10,000원, 30만원 이상 ~ 60만원 미만 20,000원, 60만원 이상 ~ 100만원 미만 30,000원, 100만원 이상 ~ 150만원 미만 40,000원, 150만원 이상 50,000원 할인 쿠폰을 제공합니다. 이 할인 쿠폰의 유효 기간은 n년입니다.',
    '포인트의 유효기간은 탑승일 기준 3년입니다.',
  ],
};
