export default {
  '201201': {
    amount: 313780,
    isInLowestGroup: false,
    noFlights: false,
    soldOut: false,
    isLowestPrice: true,
  },
  '201202': {
    amount: 313780,
    isInLowestGroup: false,
    noFlights: false,
    soldOut: false,
    isLowestPrice: true,
  },
  '201203': {
    amount: 313780,
    isInLowestGroup: false,
    noFlights: false,
    soldOut: false,
    isLowestPrice: true,
  },
  '201204': {
    amount: 313780,
    isInLowestGroup: false,
    noFlights: false,
    soldOut: false,
    isLowestPrice: true,
  },
  '201205': {
    amount: 313780,
    isInLowestGroup: false,
    noFlights: false,
    soldOut: false,
    isLowestPrice: true,
  },
  '201206': {
    amount: 313780,
    isInLowestGroup: false,
    noFlights: false,
    soldOut: false,
    isLowestPrice: true,
  },
  '201207': {
    amount: 313780,
    isInLowestGroup: false,
    noFlights: false,
    soldOut: false,
    isLowestPrice: true,
  },
  '201208': {
    amount: 313780,
    isInLowestGroup: false,
    noFlights: false,
    soldOut: false,
    isLowestPrice: true,
  },
  '201209': {
    amount: 313780,
    isInLowestGroup: false,
    noFlights: false,
    soldOut: false,
    isLowestPrice: true,
  },
  '201210': {
    amount: 313780,
    isInLowestGroup: false,
    noFlights: false,
    soldOut: false,
    isLowestPrice: true,
  },
  '201211': {
    amount: 313780,
    isInLowestGroup: false,
    noFlights: false,
    soldOut: false,
    isLowestPrice: true,
  },
  '201212': {
    amount: 313780,
    isInLowestGroup: false,
    noFlights: false,
    soldOut: false,
    isLowestPrice: true,
  },
  '201213': {
    amount: 313780,
    isInLowestGroup: false,
    noFlights: false,
    soldOut: false,
    isLowestPrice: true,
  },
  '201214': {
    amount: 313780,
    isInLowestGroup: false,
    noFlights: false,
    soldOut: false,
    isLowestPrice: true,
  },
  '201215': {
    amount: 313780,
    isInLowestGroup: false,
    noFlights: false,
    soldOut: false,
    isLowestPrice: true,
  },
  '201216': {
    amount: 313780,
    isInLowestGroup: false,
    noFlights: false,
    soldOut: false,
    isLowestPrice: true,
  },
  '201217': {
    amount: 313780,
    isInLowestGroup: false,
    noFlights: false,
    soldOut: false,
    isLowestPrice: true,
  },
  '201218': {
    amount: 313780,
    isInLowestGroup: false,
    noFlights: false,
    soldOut: false,
    isLowestPrice: true,
  },
  '201219': {
    amount: 313780,
    isInLowestGroup: false,
    noFlights: false,
    soldOut: false,
    isLowestPrice: true,
  },
  '201220': {
    amount: 313780,
    isInLowestGroup: false,
    noFlights: false,
    soldOut: false,
    isLowestPrice: true,
  },
  '201221': {
    amount: 313780,
    isInLowestGroup: false,
    noFlights: false,
    soldOut: false,
    isLowestPrice: true,
  },
  '201222': {
    amount: 313780,
    isInLowestGroup: false,
    noFlights: false,
    soldOut: false,
    isLowestPrice: true,
  },
  '201223': {
    amount: 313780,
    isInLowestGroup: false,
    noFlights: false,
    soldOut: false,
    isLowestPrice: true,
  },
  '201224': {
    amount: 356780,
    isInLowestGroup: false,
    noFlights: false,
    soldOut: false,
    isLowestPrice: false,
  },
  '201225': {
    amount: 356780,
    isInLowestGroup: false,
    noFlights: false,
    soldOut: false,
    isLowestPrice: false,
  },
  '201226': {
    amount: 356780,
    isInLowestGroup: false,
    noFlights: false,
    soldOut: false,
    isLowestPrice: false,
  },
  '201227': {
    amount: 356780,
    isInLowestGroup: false,
    noFlights: false,
    soldOut: false,
    isLowestPrice: false,
  },
  '201228': {
    amount: 356780,
    isInLowestGroup: false,
    noFlights: false,
    soldOut: false,
    isLowestPrice: false,
  },
  '201229': {
    amount: 356780,
    isInLowestGroup: false,
    noFlights: false,
    soldOut: false,
    isLowestPrice: false,
  },
  '201230': {
    amount: 356780,
    isInLowestGroup: false,
    noFlights: false,
    soldOut: false,
    isLowestPrice: false,
  },
  '201231': {
    amount: 356780,
    isInLowestGroup: false,
    noFlights: false,
    soldOut: false,
    isLowestPrice: false,
  },
};
